services:
    hangman_datastore.word_repository:
        class: Hangman\Bundle\DatastoreBundle\Repository\ORM\WordRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - Hangman\Bundle\DatastoreBundle\Entity\ORM\Word
    hangman_datastore.game_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - Hangman\Bundle\DatastoreBundle\Entity\ORM\Game
