hangman_api_game_start:
    path:     /games
    defaults: { _controller: HangmanApiBundle:HangmanGame:start }
    methods:  [POST]

hangman_api_game_guess:
    path:     /games/{gameId}
    defaults: { _controller: HangmanApiBundle:HangmanGame:guess }
    methods:  [PUT]
    requirements:
        gameId:  \d+

