services:
    hangman_api.game.controller:
        class: "Hangman\Bundle\ApiBundle\Controller\HangmanGameController"
        arguments:
            - @hangman_game.game_service
            - @router
