services:
  hangman_game.game_service:
      class: Hangman\Bundle\GameBundle\Service\GameService
      arguments:
          - @doctrine.orm.entity_manager
          - @hangman_datastore.word_repository
